flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- aeson-1.2.3.0
- binary-0.8.5.1
- directory-1.3.1.5
- extra-1.6
- megaparsec-6.4.0
- parser-combinators-0.4.0
- pretty-terminal-0.1.0.0
- unix-2.7.2.2
- websockets-0.11.2.0
resolver: lts-9.10
