version: 2.1
jobs:
  docs-deploy:
    docker:
      - image: circleci/node:11.10.1
    working_directory: ~/penrose/penrose-web
    steps:
      - checkout:
          path: ~/penrose
      - run:
          name: Install deps
          command: |
            sudo npm install -g --silent gh-pages
            npm install
            git config user.email "ci-build@penrose.ink"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "e0:22:08:03:8f:eb:1c:b7:59:4e:48:00:6d:2d:a7:be"
      - run:
          name: Generate docs
          command: npm run docs
      - run:
          name: Add nojekyll
          command: touch docs/.nojekyll
      - run:
          name: Deploy to gh-pages
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/
  build:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout:
          path: ~/penrose
      - restore_cache:
          key: dependency-cache-{{ checksum "~/penrose/package.json" }}-{{ arch }}
      - run:
          name: Install Lerna
          command: npm install -g lerna
          working_directory: ~/penrose
      - run:
          name: Install npm deps
          command: npm install
          working_directory: ~/penrose
      - save_cache:
          key: dependency-cache-{{ checksum "~/penrose/package.json" }}-{{ arch }}
          paths:
            - ~/penrose/node_modules
      - run:
          name: Build normally
          command: lerna bootstrap
          resource_class: large
          working_directory: ~/penrose
      - run:
          name: Test
          command: npm test
          working_directory: ~/penrose/
      # - store_artifacts:
      #     path: ~/penrose/penrose-web/build
      #     destination: penrose-web-built
workflows:
  version: 2.1
  build_other_branches:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master

  build_master_deploy:
    jobs:
      - docs-deploy:
          filters:
            branches:
              only: master
      - build_frontend:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              only: master
      - headless_test:
          requires:
            - build
          filters:
            branches:
              only: master
